# Generated by Django 3.0.3 on 2020-02-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='New', max_length=100),
        ),
    ]
