# Generated by Django 3.0.3 on 2020-02-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('User', 'User')], default='New', max_length=100),
        ),
    ]
