# Generated by Django 3.0.3 on 2020-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doctorPK',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
